// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywgvfrarnsakfwfhhczy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3Z3ZmcmFybnNha2Z3ZmhoY3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzE1OTQsImV4cCI6MjA2NTI0NzU5NH0.eJXM2oLQilZjFsniXAsYQBtP3Wn2cqb9GHWbpeaZpIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);